### ISSUE TITLE
Support for playlists

### ISSUE THREAD

**Issue by riotrah** [ph1p/fyfill#1]
Hi!

I have a playlist of album arts for inspiration for my own album art designs. I have struggled to find some solution to either see a grid of them in the app, on the web, or within figma via any plugins. Yours is the closest I think to being able to do this.

I can also contribute if you desire, but I firstly wanted to check if this project is active.

Thanks for this anyways, it's a great plugin!

(BTW also, for some reason the oauth flow doesn't work with Opera GX, but _does_ with Chrome)

**Comment by ph1p** [comment]
Hi! I think it's not a problem, I'll take a look :) Thanks for the suggestion.

And I'll also take a look at the Opera GX - Bug

**Comment by ph1p** [comment]
I have started to implement it. It is functional, but still needs to be polished. I'll let you know when it's released. (:

**Comment by riotrah** [comment]
Thanks! Much awaited!

**Comment by riotrah** [comment]
I've done a lot of macgyvering with the spotify API for manually doing this, and I had to implement some boilerplate for handling the payload `limit` and `offset` (which I think default to `50`). 

I'm sure my 500 track playlist is probs an outlier for the Figma side of things anyways, but since the linked PR is quite large so I was curious if it does/will consider auto pulling `next` pages

**Comment by ph1p** [comment]
Shipped! And autoscroll is already implemented :)
